repos: # reference: mlflow repo(https://github.com/mlflow/mlflow/blob/master/.pre-commit-config.yaml)
- repo: local
  hooks:
  - id: ruff
    name: ruff
    entry: poetry run ruff
    language: system
    types: [python]
    stages: [commit]

  - id: black
    name: black
    entry: poetry run black
    language: system
    types: [python]
    stages: [commit]
